# Configuration for Remove-Outside-Collaborators

# Turn on Monitor Mode [SET ON BY DEFAULT]. In this mode the repo visibility is not modified and only an Issue is created
monitorOnly: true

# Enables detection of repos that change visibility from private to public (not just newly created ones)
enableCollaboratorRemoval: true

# Issue Title when an Outside Collaborator is added
removedIssueTitle: '[CRITICAL] An Outside Collaborator has been added to this Repository!'

# Issue Body when an Outside Collaborator is added
removedIssueBody: 'NOTE: Outside Collaborators are disabled for this organization! This member has been removed. Please contact an admin to override.'

# Issue Title when monitor mode is enabled
monitorIssueTitle: '[CRITICAL] Outside Collaborator Added'

# Issue Body when monitor mode is enable
monitorIssueBody: 'Please note that the adding of Outside Collaborators is prohibited!'

# Users/Groups that should be cc'ed on the issue. Should be users/groups separated by a space.
# ccList: '@user123 @user456'

# Collaborators to exclude in detection. Should be a List of Strings.
# excludeRepos: ['user1', 'user2']
